name: Team Project Config
version: 1.0.0
schema: v1
context:
  - provider: clipboard
  - provider: code
  - provider: debugger
    params:
      stackDepth: 3
  - provider: open
    params:
      onlyPinned: true
  - provider: diff
  - provider: file
  - provider: problems
  - provider: terminal
  - provider: http
    params:
      url: "!<api_url>"
      headers:
        - Authorization: Bearer !<token>
