name: UI Worker
version: "1.3"
schema: v1
description: include only src folder
models:
  - name: Gemini 2.5 Flash
    provider: openai
    model: gemini-2.5-flash
    apiBase: http://localhost:7331/v1
    roles:
      - chat
      - edit
      - apply
      - summarize
context: []
rules: []
prompts: []
docs: []
mcpServers: []
